export const GET_ALL_USERS_REQUEST="GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS="GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE="GET_ALL_USERS_FAILURE";

export const FIND_USER_BY_ID_REQUEST="FIND_USER_BY_ID_REQUEST";
export const FIND_USER_BY_ID_SUCCESS="FIND_USER_BY_ID_SUCCESS";
export const FIND_USER_BY_ID_FAILURE="FIND_USER_BY_ID_FAILURE";
