export const SHIPP_ORDER_SUCCESS="SHIPP_ORDER_SUCCESS";
export const SHIPP_ORDER_REQUEST="SHIPP_ORDER_REQUEST";
export const SHIPP_ORDER_FAILURE="SHIPP_ORDER_FAILURE";

export const GET_ORDER_SUCCESS="GET_ORDER_SUCCESS";
export const GET_ORDER_REQUEST="GET_ORDER_REQUEST";
export const GET_ORDER_FAILURE="GET_ORDER_FAILURE";

export const CONFIRM_ORDER_SUCCESS="CONFIRM_ORDER_SUCCESS";
export const CONFIRM_ORDER_REQUEST="CONFIRM_ORDER_REQUEST";
export const CONFIRM_ORDER_FAILURE="CONFIRM_ORDER_FAILURE";

export const DELIVER_ORDER_SUCCESS="DELIVER_ORDER_SUCCESS";
export const DELIVER_ORDER_REQUEST="DELIVER_ORDER_REQUEST";
export const DELIVER_ORDER_FAILURE="DELIVER_ORDER_FAILURE";

export const DELETE_ORDER_SUCCESS="DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_REQUEST="DELETE_ORDER_REQUEST";
export const DELETE_ORDER_FAILURE="DELETE_ORDER_FAILURE";

export const PLACE_ORDER_SUCCESS="PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_REQUEST="PLACE_ORDER_REQUEST";
export const PLACE_ORDER_FAILURE="PLACE_ORDER_FAILURE";

export const CANCELLED_ORDER_SUCCESS="CANCELLED_ORDER_SUCCESS";
export const CANCELLED_ORDER_REQUEST="CANCELLED_ORDER_REQUEST";
export const CANCELLED_ORDER_FAILURE="CANCELLED_ORDER_FAILURE";